### PR TITLE
Added twilight version of appimage installer

### PR DESCRIPTION
**Pull request by LeMoonStar**
Currently, installing Zen Twilight on Linux is quite annoying as there is no flatpak and the installer script doesn't support Twilight.
I've taken a few minutes to create a modified version of the installer script for twilight, making using Twilight on Linux much more convenient.

This script can also be used to solve https://github.com/zen-browser/www/issues/219, linking to this version of the script instead of the "stable" one, when downloading Twilight.

### CODE REVIEW

**Comment by LeMoonStar** [comment]
This version of the script also includes the fix made in #7.

**Comment by mr-cheffy** [comment]
I dont think making a new installer script is the most ideal path. Maybe it should be an option inside the installer it's self, sorry!

**Comment by LeMoonStar** [comment]
> I dont think making a new installer script is the most ideal path. Maybe it should be an option inside the installer it's self, sorry!
@mauro-balades 

While I at first also thought adding Twilight as an option to the script is a better approach - I do think seperating Zen and Zen Twilight is the better approach. Installing and using Zen Twilight should only be done when the user knows that they're doing. Offering it directly in the normal install script might lead to users installing Twilight without giving it much thought.

Zen and Zen Twilight are separated like this with every other form of distribution as well - They are always separate downloads or packages.

**Comment by mr-cheffy** [comment]
Having 2 separate scripts can be tedious to mantain. It's better to have a centralized one. 

In order to people install twilight will literally need to spell `twilight` in the arguments. Literally no difference between this and having a different URL

**Comment by LeMoonStar** [comment]
making it a command line argument is indeed a good idea!
I can try implementing it, if you don't already plan on doing that yourself.

**Comment by LeMoonStar** [comment]
#8 Implements twilight installation functionality in the already existing script.

**Pull request closed without merging**
